# Carambus Local Server Mode Docker Compose Configuration
# Wird nach 'rake mode:local' verwendet

version: '3.8'

services:
  # PostgreSQL Database (Local Server)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: carambus_local_development
      POSTGRES_USER: www_data
      POSTGRES_PASSWORD: carambus_local_development_password
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
      # Optional: Database dump importieren
      - ../../docker-production-data/carambus_production_20250805_224054.sql.gz:/docker-entrypoint-initdb.d/carambus_production_20250805_224054.sql.gz
    ports:
      - "5432:5432"  # Local Server verwendet Port 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U www_data -d carambus_local_development"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache (Local Server)
  redis:
    image: redis:7-alpine
    volumes:
      - redis_local_data:/data
    ports:
      - "6379:6379"  # Local Server verwendet Port 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Rails Application (Local Server)
  web:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.development
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://www_data:carambus_local_development_password@postgres:5432/carambus_local_development
      REDIS_URL: redis://redis:6379/0
      RAILS_SERVE_STATIC_FILES: true
      RAILS_LOG_TO_STDOUT: true
      RAILS_HOST: 0.0.0.0
      RAILS_PORT: 3000
      DEPLOYMENT_TYPE: LOCAL_SERVER
      # Asset-Build aktivieren
      RAILS_ASSETS_PRECOMPILE: true
    volumes:
      # Source Code
      - ../..:/app
      # Credentials (read-only)
      - ../../config/credentials:/app/config/credentials:ro
      # Persistente Daten
      - storage_local_data:/app/storage
      - log_local_data:/app/log
      - tmp_local_data:/app/tmp
      # Node modules (für bessere Performance)
      - node_modules_local_data:/app/node_modules
    ports:
      - "3000:3000"  # Local Server auf Port 3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Asset-Build und Server starten
    command: >
      bash -c "
        echo '🔨 Building assets...' &&
        yarn build:css &&
        yarn build &&
        echo '📦 Precompiling Rails assets...' &&
        bundle exec rails assets:precompile &&
        echo '🚀 Starting Rails Local Server...' &&
        bundle exec rails server -b 0.0.0.0 -p 3000
      "

volumes:
  postgres_local_data:
  redis_local_data:
  storage_local_data:
  log_local_data:
  tmp_local_data:
  node_modules_local_data:

