Style/HashSyntax:
  Enabled: false
Metrics/AbcSize:
  Max: 60
Metrics/MethodLength:
  Max: 150
Metrics/BlockLength:
  Max: 100
Metrics/ClassLength:
  Max: 500
Metrics/PerceivedComplexity:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 100
Metrics/BlockNesting:
  Max: 6
Metrics/ParameterLists:
  Max: 15
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/EmptyElse:
  Enabled: false
Naming/VariableNumber:
  Enabled: false

# Enable new cops by default
AllCops:
  NewCops: enable