version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.raspberry-pi
    image: carambus/carambus:raspberry-pi
    container_name: carambus_app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://www_data:carambus_password@db:5432/carambus_production
      - REDIS_URL=redis://redis:6379/0
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ./config:/rails/config
      - ./storage:/rails/storage
      - ./log:/rails/log
      - ./public:/rails/public
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: arm32v7/postgres:13
    container_name: carambus_db
    environment:
      - POSTGRES_DB=carambus_production
      - POSTGRES_USER=www_data
      - POSTGRES_PASSWORD=carambus_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U www_data -d carambus_production"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: arm32v7/redis:6-alpine
    container_name: carambus_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  nginx:
    image: arm32v7/nginx:alpine
    container_name: carambus_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: carambus_network 