version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: carambus_postgres
    environment:
      POSTGRES_DB: carambus_production
      POSTGRES_USER: carambus
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-carambus_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carambus -d carambus_production"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: carambus_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Rails Application
  web:
    build: .
    container_name: carambus_web
    environment:
      RAILS_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: carambus_production
      POSTGRES_USER: carambus
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-carambus_password}
      REDIS_URL: redis://redis:6379/0
      RAILS_MASTER_KEY: 411296fb04860ea0d3d5cb1e6800f7e6
      SECRET_KEY_BASE: 0e89b3956a771ed0df3f2849fa7d5220f79ad76f96e707fe4c298d29645451d7fb9b43de0f73e9e10f4df134aeb2402b83addfa6ff31fd72afc2107a76f8d226
      RAILS_SERVE_STATIC_FILES: true
      RAILS_LOG_TO_STDOUT: true
    volumes:
      - ./storage:/app/storage
      - ./log:/app/log
      - ./tmp:/app/tmp
    ports:
      - "3000:3000"
    command: bundle exec rails server -b 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: carambus_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: carambus_network 