---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: carambus_local_phat_development
  host: localhost

test:
  <<: *default
  database: carambus_local_phat_test
  host: localhost

production:
  <<: *default
  database: carambus_local_phat_production
  username: www-data
  password: toS6E7tARQafHCXz
  host: localhost
