--- !ruby/object:Jumpstart::Configuration
application_name: Carambus
business_name: Ullrich-IT-Consulting
domain: example.com
support_email: gernot.ullrich@gmx.de
default_from_email: Jumpstart <support@example.com>
business_address: |-
  Sandstückenweg 15
  22869 Schenefeld
background_job_processor: async
email_provider: ''
personal_accounts: true
livereload: falsenaments
register_with_account: false
carambus_api_url: "http://api.carambus.de:8088"
#carambus_api_url: "http://localhost:3333"
small_table_no: 4
large_table_no: 4
pool_table_no: 4
snooker_table_no: 4
carambus_api_access_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjQwcVZXQUNxZDMtcElFakNjZndjQSJ9.eyJpc3MiOiJodHRwczovL2Rldi1yNGRqbXZhYS5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXFBSlk3ek5Nc3cwamlUaGNjUXlLT08xV3lqS1AwQUNAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vYXBpLmNhcmFtYnVzLmRlIiwiaWF0IjoxNjYyMTExNjM5LCJleHAiOjE2NjIxOTgwMzksImF6cCI6ImFxQUpZN3pOTXN3MGppVGhjY1F5S09PMVd5aktQMEFDIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.bLW9HIbPjugBrIPxdTrgqGZx0lpyxFkt50d9O2d9nbZHiYDvCeAZddkxzMiAzgFpJUSlDMdI6I3UbXCuUFJGd12vou9Wb77nTHQWK1H44B5Hq8twnbxDBfgzGTNd2mGo46WwEIXSauCYhy7NbeIAJfCXsW-aEA4of2a28SZshg5zkwtuj_lL3GnWryeA0qLS42UAtqao5UFpZfpawIIORH9rSxtAJ42zsbWt1tVct3g_je8y40O3SRKaEaT0LY0OD8ICEs9DryvhfxFKylSmIu3jUhpdLfimvuNvqAf6crDnlXIVlgZrmXxzcZKZv2ohtZJGbxLQHFY1ZjTIYjBBJg"
carambus_api_token_type: "Bearer"
carambus_api_token_expire_at: "2022-09-02 21:40:39 +0200"
