  # Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 028f0cdffcd1446630fddd1163de81e6cf78fbf33e2a356f4dfd6e20eb3b5a27af14e40172f3a1e1a0e2a7fdbf34fd70b1aef6aa9e218b1dd4468ab9487f5a53

test:
  secret_key_base: 678cd6a3f101c77abceb057a9a92cdcf3f31be878c6cc7a80148d6c1e6fa334f9f3e562feea9d4a42214786e3ba4150ffe93fa2f0e6bb7188df983f3f10704ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 955df46ab0b1fc40bbc058ecade6eec3d417ab36bd089ce86db3407476f9f01a155417b22b30540770781a955667705531e1bfcc8de8f2acfb74e947b76b0315
