# frozen_string_literal: true

require "test_helper"

# Phase 38.5 D-13 — RED-tests for latent BK-* bugs.
#
# Today: ALL FOUR tests FAIL (bug behaviour).
# After Plans 04+05 land: ALL FOUR turn GREEN automatically.
# Do NOT edit this file in Plan 06 — that file is the GSD verification contract.
#
# Documented bugs (RED→GREEN):
#
# D-11 (Test 1): BK-2kombi DZ-Phase. Player A shoots -3. Today the value lands
#   signed on A's own score (because `bk_credit_negative_to_opponent?` matches
#   only `bk_2plus`, not the DZ phase of `bk2_kombi`). Correct behaviour: +3
#   credited to the OPPONENT, A's score unchanged.
#
# D-12 (Tests 2-4): BK-2 / BK50 / BK100 single-set play. Player A shoots -2 with
#   current inning value 0. Today the gate at score_engine.rb:84 rejects the input
#   (because `allow_negative_scores?` matches only `bk2_kombi`) and the value is
#   not stored. Correct behaviour: -2 stays signed on A's own score.
#
# Both bugs disappear automatically once:
#   - Plan 03 seeds Discipline.data with `allow_negative_score_input=true` and
#     `negative_credits_opponent=true|false` for BK-2plus / BK-2 / BK50 / BK100.
#   - Plan 04 rewrites the two ScoreEngine predicates to read
#     `!!data["allow_negative_score_input"]` / `!!data["negative_credits_opponent"]`.
#   - Plan 05's bake-hook writes the resolver result into TableMonitor.data at
#     start_game and at set boundaries.
#
# These tests skip the resolver entirely and seed the post-resolver state directly
# in `data` so that they pass deterministically AFTER the predicate rewrite WITHOUT
# requiring Plan 02's resolver to run. This decouples Plan 01 from Plan 02 — Plan 01
# ships independently in Wave 1.
class BkParamLatentBugsTest < ActiveSupport::TestCase
  # Build the minimal data Hash needed by ScoreEngine#add_n_balls. Mirrors the
  # post-resolver state (allow_negative_score_input / negative_credits_opponent /
  # effective_discipline) so the test passes once the predicate body is rewritten
  # to read those keys (D-09).
  def build_data_hash(free_game_form:, effective_discipline:, allow_negative_score_input:,
                      negative_credits_opponent:, kickoff: "playera")
    {
      "free_game_form" => free_game_form,
      "effective_discipline" => effective_discipline,
      "allow_negative_score_input" => allow_negative_score_input,
      "negative_credits_opponent" => negative_credits_opponent,
      "current_inning" => { "active_player" => kickoff, "balls" => 0 },
      "current_kickoff_player" => kickoff,
      "balls_on_table" => 0,
      "balls_counter" => 0,
      "balls_counter_stack" => [],
      "extra_balls" => 0,
      "allow_overflow" => nil,
      "innings_goal" => "0",
      "playera" => {
        "result" => 0,
        "innings" => 0,
        "innings_list" => [],
        "innings_redo_list" => [0],
        "innings_foul_list" => [],
        "innings_foul_redo_list" => [0],
        "balls_goal" => "0",
        "fouls_1" => 0,
        "hs" => 0,
        "gd" => "0.00",
        "discipline" => "BK2-Kombi"
      },
      "playerb" => {
        "result" => 0,
        "innings" => 0,
        "innings_list" => [],
        "innings_redo_list" => [0],
        "innings_foul_list" => [],
        "innings_foul_redo_list" => [0],
        "balls_goal" => "0",
        "fouls_1" => 0,
        "hs" => 0,
        "gd" => "0.00",
        "discipline" => "BK2-Kombi"
      },
      "ba_results" => { "Sets1" => 0, "Sets2" => 0, "Innings1" => 0, "Innings2" => 0 }
    }
  end

  # ---------------------------------------------------------------------------
  # D-11 BUG (RED→GREEN): BK-2kombi DZ-Phase, negative input must credit opponent
  # ---------------------------------------------------------------------------

  test "BK-2kombi DZ-Phase: -3 credits opponent (D-11 RED→GREEN)" do
    data = build_data_hash(
      free_game_form: "bk2_kombi",
      effective_discipline: "bk_2plus",
      allow_negative_score_input: true,
      negative_credits_opponent: true
    )
    engine = TableMonitor::ScoreEngine.new(data, discipline: nil)
    engine.add_n_balls(-3, "playera")

    assert_equal 3, data["playerb"]["innings_redo_list"][-1],
                 "BK-2kombi DZ: -3 from A must credit B with +3 (D-11)"
    assert_equal 0, data["playera"]["innings_redo_list"][-1],
                 "BK-2kombi DZ: A's score must stay 0 when -3 routes to opponent (D-11)"
  end

  # ---------------------------------------------------------------------------
  # D-12 BUG (RED→GREEN): negative input stays signed on shooter's own score
  # for BK-2 / BK50 / BK100 single-set forms (no clamp to 0, no gate-rejection).
  # ---------------------------------------------------------------------------

  test "BK-2 single-set: -2 stays signed at player (D-12 RED→GREEN)" do
    data = build_data_hash(
      free_game_form: "bk_2",
      effective_discipline: "bk_2",
      allow_negative_score_input: true,
      negative_credits_opponent: false
    )
    engine = TableMonitor::ScoreEngine.new(data, discipline: nil)
    engine.add_n_balls(-2, "playera")

    assert_equal(-2, data["playera"]["innings_redo_list"][-1],
                 "BK-2: -2 must stay signed on A's own score, NOT clamp to 0 (D-12)")
  end

  test "BK50 single-set: -2 stays signed at player (D-12 RED→GREEN)" do
    data = build_data_hash(
      free_game_form: "bk50",
      effective_discipline: "bk50",
      allow_negative_score_input: true,
      negative_credits_opponent: false
    )
    engine = TableMonitor::ScoreEngine.new(data, discipline: nil)
    engine.add_n_balls(-2, "playera")

    assert_equal(-2, data["playera"]["innings_redo_list"][-1],
                 "BK50: -2 must stay signed on A's own score, NOT clamp to 0 (D-12)")
  end

  test "BK100 single-set: -2 stays signed at player (D-12 RED→GREEN)" do
    data = build_data_hash(
      free_game_form: "bk100",
      effective_discipline: "bk100",
      allow_negative_score_input: true,
      negative_credits_opponent: false
    )
    engine = TableMonitor::ScoreEngine.new(data, discipline: nil)
    engine.add_n_balls(-2, "playera")

    assert_equal(-2, data["playera"]["innings_redo_list"][-1],
                 "BK100: -2 must stay signed on A's own score, NOT clamp to 0 (D-12)")
  end
end
